- name: Setup default git configuraiton
  become: yes
  become_user: "{{user}}"
  git_config:
    name="{{ item.name }}"
    scope=global
    value="{{ item.value }}"
  with_items:
    - {name: "user.email", value: "{{email}}" }
    - {name: "ui.color", value: "True" }
