- name: install yarn
  pacman: name=yarn state=present

- name: Install npm global packages
  npm:
    name: "{{item}}"
    global: yes
  with_items:
  - "@angular/cli"
  - "tslint"
  - "cordova"
  - "ionic"
