#- name: Install node and set version
#  shell: >
#    /bin/bash -c "source ~/.nvm/nvm.sh && nvm install node && nvm alias default node"
#    creates=/home/{{ ansible_user_id }}/.nvm/alias

- name: Install npm global packages
  npm:
    name: "{{item}}"
    global: yes
  with_items:
  - "@angular/cli"
  - "tslint"
  - "cordova"
  - "ionic"
